chore(cd): add post startup helth check

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -44,10 +44,15 @@ jobs:
           DB_APP_PASSWORD: ${{ secrets.DB_APP_PASSWORD }}
           DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
         run: |
-            echo "DB_APP_PASSWORD: ${DB_APP_PASSWORD}"
-            echo "DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}"
             cd ./MandoWebApp
             docker-compose pull
             docker-compose up -d
             sleep 240
             docker-compose logs
+            CONTAINER_STATUS=$(docker container inspect -f '{{.State.Status}}' mando-app)
+            if [ "${CONTAINER_STATUS}" == "running" ]; then
+              echo "Container mando-app started successfully."
+            else
+              echo "ERROR: mando-app container is in state: ${CONTAINER_STATUS}"
+              exit 1
+            fi
